tty: fix clang 17 build errors
drivers/tty/diag/tty_diag.c:323:38: error: a function declaration
without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
void tty_diag_channel_abandon_request()
                                     ^
                                      void

drivers/tty/diag/tty_diag.c:333:36: error: a function declaration
without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
int tty_diag_get_dbg_ftm_flag_value()
                                   ^
                                    void
2 errors generated.

Change-Id: I76f72b1037afaf473956345229fea19d7882c52b