modules:tfa98xx:delete time printk
cherrypick from (CR)
- fix compile fail.
  error: 'start_time' may be used uninitialized in this function
  [-Werror=maybe-uninitialized]
- just printk start time. delete it.

Change-Id: I846597f1227e958b1360d0cfd61756a67e56c9a1
Signed-off-by: liaohj <liaohj@mt.com>
Reviewed-on: https://gerrit.mot.com/1260694
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Minghui Wei <weimh1@motorola.com>
Reviewed-by: Wanlong Zhou <zhouwl@motorola.com>
Reviewed-by: Huosheng Liao <liaohs@motorola.com>
Submit-Approved: Jira Key
(cherry picked from commit b9b7b207c4b80f8e99ecbd0dcf0573525dc88a66)
Reviewed-on: https://gerrit.mot.com/1393913
Reviewed-by: Hujun Liao <liaohj@motorola.com>