Resolve compilation errors with unused parameters "ret"
TP:
warning unused variable 'ret' error, forbidden warning:fts.c:4034.

Change-Id: I10a19d48f54e601c1e0f5ff230bd219c830d441f
Reviewed-on: https://gerrit.mot.com/1925688
Tested-by: Jira Key
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key